In [24]:
import pandas as pd

from src.plotting import set_plotting_style
from src.data import load_csv_df

In [25]:
# Already prepared accent palette applying using function from mine src module (plotting)
set_plotting_style()

In [26]:
DF_PATH = "../data/final/final_df.csv"

# Safely loading dataframe using function from mine src module (data)
df = load_csv_df(
    df_path=DF_PATH,
)

Successfully loaded dataframe: ..\data\final\final_df.csv
Dataframe has: 195 rows / 10 columns
Dataframe size: 0.015MB

In [27]:
display(df.head(10))

,Land in km2,Inland water in km2,% water,Population,Population density,HDI,Fertility rate,Land per capita,Dev demographic index,Cluster
0,1.898592,1.896052,0.945416,1.364055,-1.610271,0.617095,-0.838589,1.425415,0.736919,-1
1,1.693211,1.950900,1.748935,0.821007,-2.062275,1.338322,-1.031456,1.662323,1.401580,-1
2,1.702040,1.641558,0.553990,2.339697,0.396877,0.381180,-1.487041,0.462444,1.455976,-1
3,1.695282,1.727949,0.896471,1.730530,-0.618881,1.331581,-0.631126,0.888328,0.911489,-1
4,1.668019,1.229801,-0.525475,1.529182,-0.870403,0.307035,-0.681783,1.013324,0.407318,0
5,1.634338,1.246011,-0.378489,0.649221,-2.146676,1.466390,-0.618582,1.752580,0.970302,-1
6,1.302941,1.680265,1.834193,2.347152,1.191770,-0.373748,-0.274086,0.028396,-0.252966,-1
7,1.274005,1.168525,0.080409,0.870585,-1.156699,0.839530,-0.785489,1.077025,0.806183,0
8,1.269254,1.025635,-0.311016,0.520129,-1.689743,0.650798,0.688068,1.391416,-0.338725,0
9,1.225509,-1.604328,-1.112012,0.879156,-1.035269,0.152005,0.424904,1.007359,-0.407311,-1

In [30]:
ORIGINAL_DF_PATH = "../data/raw/raw-data.csv"

original_df = load_csv_df(
    df_path=ORIGINAL_DF_PATH
)

df.index = original_df["Country name"]
cluster_profiles = df.groupby("Cluster").mean(numeric_only=True)
display(cluster_profiles.head(10))

Successfully loaded dataframe: ..\data\raw\raw-data.csv
Dataframe has: 195 rows / 10 columns
Dataframe size: 0.024MB

,Land in km2,Inland water in km2,% water,Population,Population density,HDI,Fertility rate,Land per capita,Dev demographic index
Cluster,,,,,,,,,
-1,-0.059995,-0.242862,-0.024417,-0.058720,0.080750,0.011493,0.035620,-0.199897,0.077721
0,0.323623,0.418223,0.233027,0.307365,-0.176375,-0.027713,0.015802,0.290239,-0.032110
1,-0.551425,-1.368943,-1.022205,-0.858959,-0.285140,-0.834345,0.829699,-0.005914,-0.947853
2,-0.686958,-1.448765,-1.082276,-0.450116,0.687613,0.836159,-0.779009,-0.572269,0.806861
3,-1.402189,-1.455808,-0.777265,-1.279254,0.775133,-0.562481,0.765873,-1.088051,-0.807543
4,-1.350618,-0.944419,-0.350360,-1.048994,1.056872,0.572159,-1.033765,-1.193194,0.936388
5,-1.810490,-1.604328,-1.112012,-1.696473,0.928457,0.578491,-0.612398,-1.485601,0.500960

In [31]:
for cluster_id in sorted(df["Cluster"].unique()):
    countries = df[df["Cluster"] == cluster_id].index.tolist()

    if cluster_id == -1:
        print(f"Noise: {len(countries)} countries")
    else:
        print(f"Cluster {cluster_id}: {len(countries)} countries")
    print(", ".join(map(str, countries)))

Noise: 39 countries
Russia, Canada, China, United States, Australia, India, Algeria, Saudi Arabia, Indonesia, Libya, Mongolia, Niger, Angola, Colombia, Mauritania, Namibia, Central African Republic, Republic of the Congo, Oman, Uganda, Bangladesh, Malawi, Iceland, South Korea, Netherlands, Burundi, Haiti, Rwanda, Fiji, Cape Verde, Singapore, Andorra, Malta, Marshall Islands, San Marino, Tuvalu, Nauru, Monaco, Vatican City
Cluster 0: 126 countries
Brazil, Argentina, Kazakhstan, Democratic Republic of the Congo, Mexico, Sudan, Iran, Peru, Chad, Mali, South Africa, Ethiopia, Bolivia, Egypt, Tanzania, Nigeria, Venezuela, Pakistan, Mozambique, Turkey, Chile, Zambia, Myanmar, Afghanistan, South Sudan, France, Somalia, Ukraine, Madagascar, Botswana, Kenya, Thailand, Spain, Turkmenistan, Cameroon, Papua New Guinea, Yemen, Sweden, Uzbekistan, Morocco, Iraq, Paraguay, Zimbabwe, Norway, Japan, Germany, Finland, Vietnam, Malaysia, Ivory Coast, Poland, Italy, Philippines, Ecuador, Burkina Faso, New Zealand, Gabon, Guinea, United Kingdom, Ghana, Romania, Laos, Guyana, Belarus, Kyrgyzstan, Senegal, Syria, Cambodia, Uruguay, Suriname, Tunisia, Nepal, Tajikistan, Greece, Nicaragua, North Korea, Eritrea, Benin, Honduras, Liberia, Bulgaria, Cuba, Guatemala, Hungary, Portugal, Jordan, Serbia, Azerbaijan, Austria, United Arab Emirates, Czech Republic, Panama, Sierra Leone, Ireland, Georgia, Sri Lanka, Lithuania, Latvia, Togo, Croatia, Bosnia and Herzegovina, Costa Rica, Slovakia, Dominican Republic, Estonia, Denmark, Switzerland, Bhutan, Guinea-Bissau, Moldova, Belgium, Armenia, Solomon Islands, Albania, North Macedonia, Belize, Israel, El Salvador, Slovenia, Eswatini, Montenegro, Bahamas, The Gambia, Jamaica, Lebanon, Brunei
Cluster 1: 6 countries
Lesotho, Equatorial Guinea, Djibouti, Timor-Leste, Vanuatu, Samoa
Cluster 2: 4 countries
Kuwait, Qatar, Cyprus, Trinidad and Tobago
Cluster 3: 6 countries
Palestine, Comoros, São Tomé and Príncipe, Kiribati, Tonga, Micronesia
Cluster 4: 3 countries
Luxembourg, Mauritius, Saint Lucia
Cluster 5: 11 countries
Bahrain, Dominica, Palau, Seychelles, Antigua and Barbuda, Barbados, Saint Vincent and the Grenadines, Grenada, Maldives, Saint Kitts and Nevis, Liechtenstein