In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.data import load_csv_df
from src.plotting import set_plotting_style

In [2]:
# Already prepared accent palette applying using function from mine src module (plotting)
set_plotting_style()

In [3]:
DF_PATH = "../data/raw/raw-data.csv"

# Safely loading dataframe using function from mine src module (data)
df = load_csv_df(
    df_path=DF_PATH,
)

Successfully loaded dataframe: ..\data\raw\raw-data.csv
Dataframe has: 195 rows / 10 columns
Dataframe size: 0.024MB

In [4]:
df.info()
"""Dataframe overview:
-------------------------
- Shape: 195 rows and 10 columns
- Data types: 9 numerical features (float64) and 1 categorial features (str)
- Features: some features name is non-standard, they include spaces, special characters, and numbers
(e.g., % water, % of world population, HDI, Land in km2)
"""

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country name           195 non-null    str
 1   Total in km2           195 non-null    float64
 2   Land in km2            194 non-null    float64
 3   Inland water in km2    194 non-null    float64
 4   % water                194 non-null    float64
 5   Population             194 non-null    float64
 6   % of world population  194 non-null    float64
 7   Population density     194 non-null    float64
 8   HDI                    190 non-null    float64
 9   Fertility rate         191 non-null    float64
dtypes: float64(9), str(1)
memory usage: 15.4 KB

'Dataframe overview:\n-------------------------\n- Shape: 195 rows and 10 columns\n- Data types: 9 numerical features (float64) and 1 categorial features (str)\n- Features: some features name is non-standard, they include spaces, special characters, and numbers\n(e.g., % water, % of world population, HDI, Land in km2)\n'

In [5]:
display(df.head(5))
display(df.tail(5))
"""Dataframe inspection:
----------------------------
- 'Country name' acts as a unique row identifier and should be moved to index
- Features like 'Population' and 'Total in km2' contain massive numbers.
While '% water', '% of world population' and 'HDI' are decimal. Scaler
is strictly necessary.
"""

,Country name,Total in km2,Land in km2,Inland water in km2,% water,Population,% of world population,Population density,HDI,Fertility rate
0,Russia,17098246.0,16376870.0,721380.0,4.2,1.460283e+08,1.8,8.54,0.832,1.47
1,Canada,9984670.0,9093507.0,891163.0,8.9,4.141706e+07,0.5,4.15,0.939,1.33
2,China,9596960.0,9326410.0,270550.0,2.8,1.404890e+09,17.0,146.39,0.797,1.03
3,United States,9525067.0,9147593.0,377424.0,4.0,3.417849e+08,4.1,35.88,0.938,1.63
4,Brazil,8510346.0,8460415.0,55352.0,0.6,2.142120e+08,2.6,25.17,0.786,1.59

,Country name,Total in km2,Land in km2,Inland water in km2,% water,Population,% of world population,Population density,HDI,Fertility rate
190,San Marino,61.00,61.00,0.0,0.0,34167.0,0.0004,560.11,0.915,1.17
191,Tuvalu,26.00,26.00,0.0,0.0,10643.0,0.0001,409.35,0.689,3.10
192,Nauru,21.00,20.00,0.0,0.0,11680.0,0.0001,556.19,0.703,3.21
193,Monaco,2.00,2.00,0.0,0.0,38857.0,0.0005,19428.50,NaN,2.09
194,Vatican City,0.44,0.44,0.0,0.0,882.0,0.0000,2004.55,NaN,1.00

"Dataframe inspection:\n----------------------------\n- 'Country name' acts as a unique row identifier and should be moved to index\n- Features like 'Population' and 'Total in km2' contain massive numbers.\nWhile '% water', '% of world population' and 'HDI' are decimal. Scaler\nis strictly necessary.\n"

In [16]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
display(df.describe().T)

print(f"HDI median: {df['HDI'].median():.3f}")
print(f"% water median: {df['% water'].median():.3f}")
print(f"% water sum: {df['% water'].sum():.2f}%") # % water not in world but in specified country
"""Dataframe observation:
-------------------------
- Already see NaN in count (e.g., 'Fertility rate' missing 4 values, summary row count is 195 but
in feature is 191 instead, all features have at least 1 missing value exclude 'Total in km2').
- 'Total in km2' has correct outliers (Country have huge difference in territory).
The same applies to 'Population' and 'Population density'.
- '% water' highly skewed towards 0 (median is only 1.4%).
- 'HDI' and 'Fertility rate' have reasonable ranges but contain minor missing values.
"""

,count,mean,std,min,25%,50%,75%,max
Total in km2,195.00,685093.57,1909727.92,0.44,23082.50,118484.00,509245.00,17098246.00
Land in km2,194.00,664691.99,1840054.05,0.44,22902.50,112325.00,492412.50,16376870.00
Inland water in km2,194.00,20595.49,91053.49,0.00,11.50,1592.50,9022.50,891163.00
% water,194.00,2.57,4.10,0.00,0.10,1.40,3.18,27.80
Population,194.00,41395284.66,149140967.70,882.00,1846638.00,9244136.50,31879025.00,1429404000.00
% of world population,194.00,0.50,1.81,0.00,0.02,0.10,0.40,17.30
Population density,194.00,317.36,1524.83,2.30,33.50,86.57,202.20,19428.50
HDI,190.00,0.74,0.15,0.39,0.62,0.76,0.86,0.97
Fertility rate,191.00,2.35,1.11,0.76,1.49,1.93,3.08,5.84

HDI median: 0.762
% water median: 1.400
% water sum: 498.15%

"Dataframe observation:\n-------------------------\n- Already see NaN in count (e.g., 'Fertility rate' missing 4 values, summary row count is 195 but\nin feature is 191 instead, all features have at least 1 missing value exclude 'Total in km2').\n- 'Total in km2' has correct outliers (Country have huge difference in territory).\nThe same is in 'Population' and 'Population density'.\n- '% water' highly skewed towards 0 (median is only 1.4%).\n- 'HDI' and 'Fertility rate' have reasonable ranges but contain minor missing values.\n"